# Site settings
title: 跨 &nbsp&nbsp 墙
email: ejiasu@gmail.com
description: <p>跨越长城 &nbsp&nbsp 连接世界</p>  <p>Across the Great Wall we can reach every corner in the world. <br />这是1987年9月14日，我国与外界互联网创建了首个连接，所发出首封电子邮件。今天，我们仍将继续……</p>
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://kuaqiang.com/" # the base hostname & protocol for your site

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url:
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown
